.github/auto_assign.yml
.github/workflows/action.yml

- 이슈 넘버 #3 
-  `auto_assign.yml` 추가하기
-  GitHub `auto-assign` 앱 설치
- `action.yml` 추가
- 일단 했는데 머지를 해야 반영이 될 수 있어서 테스트용입니다.

[CHORE] PR 시 auto assignee를 추가합니다.

---

css/index.css
css/signup.css
html/main.html
html/signup.html
index.html
server/firebaseConfig.js
server/main.js
server/signin.js
server/signup.js

- 이슈 넘버 #4
- firebase SDK를 활용한 서버와 프로젝트 연결
- firebase Authentication을 활용한 로그인 기능
- firebase Realtime Database를 활용한 회원 가입 기능
- firebase Storage를 활용한 프로필 이미지 저장 기능
- ref : https://console.firebase.google.com/?hl=ko
- 코드가 더 효율적으로 동작 할 수 있는 방법을 같이 찾아봐요

feat : firebase server 연동 및 로그인 회원가입 기능 구현

---

package-lock.json
package.json

#9 
- "eslint-config-prettier"는 lint 규칙을 덮어 써 버린다고 봐서 "eslint-plugin-prettier"로 바꿨습니다.
- commit lint 관련 의존성이 dependencies에 들어가 있어 devDependencies로 옮겼습니다.

chore: package.json dependencies 수정

---

server/firebaseConfig.js

- 이슈 넘버 #[7]
- .env 파일 생성 및 firebaseConfig.js 수정
- 정상적으로 로그인, 회원가입, 값 출력하기 기능이 수행됩니다
-

chore(firebase): sdk api 설정

---

src/components/common/header/Header.js
src/pages/not-found/NotFound.js
src/styles/global.css

- 이슈 넘버 #25 
- global.css에 버튼 스타일 템플릿 만들어놨습니다. 
- 색깔만 설정해놔서, 글자크기, padding, border-radius는 설정하셔야 합니다.
- 피그마에도 각 버튼에 어떤 거 사용해야 하는지 라벨링 해놓을테니 그거 보고 사용하시면 됩니다.

[Style] 버튼 css 템플릿 생성

---

package-lock.json
package.json
server/data/users.json
src/components/ui/form/FormValidation.js
src/components/user/form/edit-profile-form/EditProfileForm.css
src/components/user/form/edit-profile-form/EditProfileForm.js
src/components/user/profile/ProfileImage.css
src/components/user/profile/ProfileImage.js
src/pages/user/edit-profile/EditProfile.css
src/pages/user/edit-profile/EditProfile.js
src/routes/Router.js

- 이슈 넘버 #18
-  EditProfile.js
-  EditProfile.css 
-  https://github.com/user-attachments/assets/7c715824-eff8-478a-b64a-2a30b03f039f
- 작명 규칙을 준수하였는가?
- 더 효율적인 방법이 존재 하는가?
- 모든 예외에 대해 처리가 진행되는가?

feat(profile): edit-profile 구현

---

src/pages/user/edit-profile/EditProfile.js

- 이슈 넘버 #[issue_number]
- 이 곳에 진행한 업무를 작성해주세요!

Feat/edit profile 재수정

---

src/components/admin/home/notice/NoticeHeader.css
src/components/admin/home/notice/NoticeHeader.js
src/components/admin/home/user-list/UserList.css
src/components/admin/home/user-list/UserList.js
src/components/admin/home/user-list/UserListHeader.css
src/components/admin/home/user-list/UserListHeader.js
src/components/common/header/Header.js
src/components/ui/button/Button.js
src/pages/admin/member/member-management/MemberManagement.js

- 이슈 넘버 #38 
- 버튼 컴포넌트에 `width`, `height` 속성은 동적으로 생성하도록 하고, `padding`을 추가합니다.
- 호버 시 `transition` 효과를 추가합니다.
- 일부 파일 경로를 수정합니다.
- 버튼 컴포넌트 도입으로 인해 제가 작성했던 컴포넌트들에 버튼 컴포넌트를 추가합니다.
- 버튼 컴포넌트에 `width`와 `height`로 지정하는 것 대신 `padding`값으로 하는 것이 더 동적으로 만들기 편리한 것 같아서 바꿨습니다.

[STYLE] 버튼 컴포넌트를 일부 수정합니다.

---

src/pages/user/peer/Peer.js
src/routes/Router.js

- 이슈 넘버 #[issue_number]
- 이 곳에 진행한 업무를 작성해주세요!

fix: peer.js edit

---

src/components/common/pagenation/Pagenation.js
src/components/user/profile/ProfileImage.js
src/pages/admin/member/member-detail/MemberDetail.js
src/pages/admin/member/member-management/MemberManagement.js
src/pages/admin/member/upload-member/UploadMember.css
src/pages/admin/member/upload-member/UploadMember.js
src/pages/index.js
src/routes/Router.js
src/utils/constants.js

[feat] 관리자 직원 업로드 기능

---

src/components/admin/notice-form/NoticeForm.css
src/components/admin/notice-form/NoticeForm.js
src/components/index.js
src/components/user/profile/ProfileImage.js
src/pages/admin/member/member-management/MemberManagement.css
src/pages/admin/member/member-management/MemberManagement.js
src/pages/admin/member/upload-member/UploadMember.css
src/pages/admin/notice/upload-notice/UploadNotice.css
src/pages/admin/notice/upload-notice/UploadNotice.js
src/pages/index.js
src/routes/Router.js

[feat] 공지 관리 업로드 구현

---

src/components/admin/home/notice/Notice.css
src/components/admin/home/notice/NoticeHeader.css
src/components/admin/home/user-list/UserList.css
src/components/admin/home/user-list/UserList.js
src/components/admin/home/user-list/UserListHeader.css
src/components/admin/notice-management/NoticeManagementHeader.css
src/components/admin/vacation-management/VacationHeader.css

- 이슈 넘버 #72 
- 메인페이지에 반응형 스타일을 추가합니다.
- 공지관리 반응형 스타일도 수정합니다.
- 메인페이지에서 직원 상세 보기를 클릭하면 상세 페이지로 이동합니다.

[STYLE] 반응형 스타일을 추가합니다.

---

server/data/time_punch.json
src/components/ui/modal/Modal.css
src/components/ui/modal/Modal.js
src/components/ui/modal/admin/adminModal.css
src/components/ui/modal/admin/adminModal.js
src/components/ui/modal/user/userModal.css
src/components/ui/modal/user/userModal.js
src/components/user/work-info/WorkInfo.js
src/pages/user/course/Course.css
src/pages/user/course/Course.js
src/pages/user/edit-profile/EditProfile.js
src/pages/user/home/Home.css
src/pages/user/home/Home.js
src/pages/user/notice/notice-list/NoticeList.css
src/pages/user/work-detail/WorkDetail.js

- 이슈 넘버 #[73]
- userModal
- adminModal

[FEAT} userModal, adminModal 

---

src/components/admin/notice-detail/NoticeDetailItem.js
src/components/admin/notice-form/NoticeForm.js
src/components/admin/notice-management/NoticeManagementHeader.css
src/pages/admin/notice/edit-notice/EditNotice.css
src/pages/admin/notice/edit-notice/EditNotice.js
src/pages/admin/notice/upload-notice/UploadNotice.js
src/pages/index.js
src/routes/Router.js
src/utils/constants.js

[feat] 관리자 공지 수정

---

src/components/admin/notice-detail/NoticeDetailItem.js
src/components/common/navbar/Navbar.js
src/components/ui/modal/Modal.css
src/components/ui/modal/admin/adminModal.css
src/components/ui/modal/admin/adminModal.js
src/components/ui/modal/user/userModal.css
src/components/ui/modal/user/userModal.js

- 이슈 넘버 #81 
- 기존에 해상도에 따라 깨지는 것을 수정했습니다.
- 호버 효과를 추가했습니다.
- 네비게이션 바에서 활성화된 메뉴가 현재 경로로만 한정되어 있었는데 현재 경로로 시작한다면 그 메뉴가 계속 활성화 되도록 설정했습니다.

[STYLE] 모달 스타일을 수정합니다.

---

server/api/admin.js
src/components/admin/notice-detail/NoticeDetailItem.js
src/components/admin/notice-profile/AttachProfileImageEvents.js
src/components/common/notice/AdminNoticeList.js
src/components/ui/modal/Modal.css
src/components/ui/modal/Modal.js
src/components/ui/modal/admin/adminModal.js
src/pages/admin/notice/edit-notice/EditNotice.js
src/pages/admin/notice/upload-notice/UploadNotice.js
src/utils/handleProfileImg.js

- 이슈 넘버 #94 
-  `firebase`에서 제공하는 메서드를 사용합니다.
- 메서드를 사용하여 API를 구현합니다. (휴가 관련, 공지사항 관련)
- `getAllNotices`을 통해 모든 공지사항을 불러옵니다.
- `getNoticeById`를 통해 단일 공지사항 불러옵니다. 
- `deleteNotice`를 통해 공지사항을 삭제합니다.
- `updateNotice`를 통해 공지사항을 수정합니다.
- `addNotice`를 통해 공지사항을 업로드합니다.
https://github.com/user-attachments/assets/cf0f3c2d-c560-46b7-ba9e-ef1fcb003303
- 할 게 많은 것 같아서 급하게 했더니 코드가 좀 많이 개판인 것 같네요,,

[SERVER] 관리자- firebase에서 공지사항 데이터 CRUD를 구현합니다.

---

server/api/admin.js
src/components/admin/home/user-list/UserList.js
src/components/admin/notice-profile/AttachProfileImageEvents.js
src/pages/admin/member/member-detail/MemberDetail.js
src/pages/admin/member/member-management/MemberManagement.js
src/pages/admin/member/upload-member/UploadMember.js
src/pages/admin/notice/upload-notice/UploadNotice.js

- 이슈 넘버 #[issue_number]
- 관리자 직원 삭제 및 업로드 구현

[server] 관리자 직원 삭제 및 업로드 구현

---

src/components/user/home/notice-gallery/NoticeGallery.css
src/components/user/home/punch-time/PunchTime.css
src/components/user/peer-list/PeerList.css
src/pages/user/notice/notice-list/NoticeList.css
src/pages/user/notice/notice-list/NoticeList.js
src/pages/user/peer/Peer.js

- 이슈 넘버 #101 
- 유저 홈페이지 css 조금 수정

[Style] user home

---

server/api/admin.js
server/api/user.js
src/components/admin/vacation-management/VacationHeader.js
src/components/admin/vacation-management/VacationList.js
src/components/ui/modal/Modal.js
src/pages/admin/notice/upload-notice/UploadNotice.js
src/utils/vacationStore.js

- 이슈 넘버 #103 
- 관리자 페이지에서 관리자용 예외 처리를 합니다. (`user.js`)
- 휴가/공가 관리 페이지에서 각 버튼에 대한 요청을 진행하여 `firebase`에 반영되도록 합니다.
- 휴가를 불러오는 과정에서 필터링과 페이지네이션마다 불러오는 것을 막고자 `store`를 사용해서 승인 수정이 일어날 때마다 새로고침됩니다.
https://github.com/user-attachments/assets/38018157-1c73-43a8-bba5-779619f97b17
- 데이터 양이 많아서 그런지 로딩이 엄청 오래 걸리네요 ㅜㅜ 사진 때문인걸까요ㅠ
- ↑ `store`로 처음 한 번의 데이터만 가져오고 나머지 페이지네이션이나 필터링 과정에서 불필요한 다시 가져오는 현상을 막았습니다. 승인 수정이 일어날 때마다 새로고침되어 새로운 데이터를 가져옵니다.
`store`는 데이터와 관련 메서드들을 하나의 객체 안에서 관리하기 위해서입니다.
또한, 클래스를 사용하면 `this`를 통해서 내부 상태에 쉽게 접근하고 수정 가능하고 그룹화가 가능합니다.
클래스를 사용함을로써 이 파일은 **데이터 관리를 위한 것**이라는 의도를 전달 가능합니다.

[FEAT] 관리자- 휴가/공가 관리 페이지에서 각 버튼에 대한 요청을 합니다.

---

server/api/admin.js
server/api/user.js
src/components/common/pagenation/Pagenation.js
src/components/ui/modal/Modal.js
src/pages/admin/member/member-detail/MemberDetail.js
src/pages/admin/member/member-management/MemberManagement.js
src/pages/admin/member/upload-member/UploadMember.css

- #100 
- 직원 등록 시 이미지 업로드 기능
- 직원 삭제 시 modal 적용

[server] 직원 삭제 modal 적용

---

index.html
src/pages/user/course/Course.js

- 이슈 넘버 #[issue_number]
- 콘솔창에 찍히는 오류 사항을 수정합니다.

[FIX] 오류 사항 수정
